version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true
    vars:
      API_DIRS: '{{.ROOT_DIR}}/api/v1alpha1/...'
      MANIFEST_OUT: '{{.ROOT_DIR}}/api/crds/manifests'
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/api/v1alpha1/... {{.ROOT_DIR}}/pkg/...'
      COMPONENTS: 'cluster-provider-kind'
      REPO_URL: 'https://github.com/openmcp-project/cluster-provider-kind'
      CHART_COMPONENTS: "[]"
      DOCKERFILE: '{{.ROOT_DIR}}/Dockerfile'
      CRDS_COMPONENTS: 'cluster-provider-kind'
      CRDS_PATH: '{{.ROOT_DIR}}/api/crds/manifests'
