version: 3

vars:
  NESTED_MODULES: api
  API_DIRS: '{{.ROOT_DIR}}/api/...'
  MANIFEST_OUT: '{{.ROOT_DIR}}/config/crd/bases'
  CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/api/...'
  COMPONENTS: 'cluster-provider-kind'
  REPO_NAME: 'https://github.com/openmcp-project/cluster-provider-kind'
  GENERATE_DOCS_INDEX: "false"

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true