# This rule is not used by the project cluster-provider-kind itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over kind.clusters.openmcp.cloud.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-provider-kind
    app.kubernetes.io/managed-by: kustomize
  name: cluster-admin-role
rules:
- apiGroups:
  - kind.clusters.openmcp.cloud
  resources:
  - clusters
  verbs:
  - '*'
- apiGroups:
  - kind.clusters.openmcp.cloud
  resources:
  - clusters/status
  verbs:
  - get
