# This rule is not used by the project cluster-provider-kind itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kind.clusters.openmcp.cloud resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-provider-kind
    app.kubernetes.io/managed-by: kustomize
  name: cluster-viewer-role
rules:
- apiGroups:
  - kind.clusters.openmcp.cloud
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kind.clusters.openmcp.cloud
  resources:
  - clusters/status
  verbs:
  - get
