---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kind.clusters.openmcp.cloud
  resources:
  - accessrequests
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kind.clusters.openmcp.cloud
  resources:
  - accessrequests/finalizers
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - kind.clusters.openmcp.cloud
  resources:
  - accessrequests/status
  - clusters/status
  verbs:
  - get
  - patch
  - update
