name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write

jobs:
  release_publish:
   uses: openmcp-project/build/.github/workflows/publish.lib.yaml@65e6b16460f72253e95d292f8c58fd9e5affa9fd # main
   secrets: inherit