name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write

jobs:
  release_publish:
   uses: openmcp-project/build/.github/workflows/publish.lib.yaml@f72e86a8123eab5790f6dce6577fc99785df2819 # main
   secrets: inherit