name: Versioned Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # we need this to be able to push tags
  pull-requests: read

jobs:
  release_tag:
    uses: openmcp-project/build/.github/workflows/release.lib.yaml@65e6b16460f72253e95d292f8c58fd9e5affa9fd # main
    secrets: inherit
