name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@f72e86a8123eab5790f6dce6577fc99785df2819 # main
    secrets: inherit
